### ISSUE TITLE
Cannot find module ' ./logo.svg' or its corresponding type declarations.

### ISSUE THREAD

**Issue by ammuhridhya** [theos/logos#102]
What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

What happens?
-------------
…

What were you expecting to happen?
----------------------------------
…

Any logs, error output, etc?
----------------------------

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …

**Toolchain Version:** …

**SDK Version:** …

**Comment by kirb** [comment]
Please fill out the issue template. Why are you trying to import an svg in TypeScript and why is this related to this project?

**Comment by L1ghtmann** [comment]
Closing due to lack of response.
