### ISSUE TITLE
Logos failes to hook NSBundle.bundleIdentifier on iOS 16

### ISSUE THREAD

**Issue by cmdlinescan** [theos/logos#107]
What are the steps to reproduce this issue?
-------------------------------------------
1. Try running this code:
%hook NSBundle
	-(NSString *)bundleIdentifier {
		return @"test";
	}
%end

What happens?
-------------
App just crashes

What were you expecting to happen?
----------------------------------
The function will hook normally without crashes. Without logos hook, its all fine

Any logs, error output, etc?
----------------------------

Any other comments?
-------------------
Works fine on my jailbroken iOS 13, crashes on iOS 16.

What versions of software are you using?
----------------------------------------
**Operating System:** iOS 16.4.1

**Toolchain Version:** idk

**SDK Version:** iOS 13 SDK

**Comment by L1ghtmann** [comment]
1) do you have a crash report? 2) are you building on iOS, OSX, or Linux? 3) assuming you're on Linux, can you share the result of `$THEOS/toolchain/linux/iphone/bin/ldid -v`? Thanks!

**Comment by L1ghtmann** [comment]
Closing due to lack of response. Feel free to re-open if the issue persists.
