### ISSUE TITLE
%property results in compile error

### ISSUE THREAD

**Issue by wvabrinskas** [theos/logos#32]
When adding a %property to a hooked class the compiler throws an error, ex: 

For: 
```
@interface SBIconController
@property (nonatomic,retain) NSMutableArray *hiddenIcons;
.....
@end  

%hook SBIconController
%property (nonatomic,retain) NSMutableArray *hiddenIcons;
....
%end
```
Result:
`error: no matching function for call to 'objc_getAssociatedObject' 
__attribute__((used)) static NSMutableArray * _logos_method$_ungrouped$SBIconController$hiddenIcons(SBIconController * __unused self, SEL __unused _cmd) { return (NSMutableArray *)objc_getAssociatedObject(self, _logos_method$_ungrouped$SBIconController$hiddenIcons); }; __attribute...`

**Comment by uroboro** [comment]
Make sure you have an updated Logos (via Theos) because this issue was solved with commit 30803da.

**Comment by wvabrinskas** [comment]
I ran `update-theos`. Is there a different command I should run?

**Comment by wvabrinskas** [comment]
@uroboro i fixed it by running `git submodule update --recursive --remote`. `update-theos` did not update the submodules
