### ISSUE TITLE
Add option to specify library path to %hookf("func")

### ISSUE THREAD

**Issue by sbingner** [theos/logos#35]
It would be good to be able to search a specific library for the symbol provided instead of always using MSFindSymbol(NULL, "symbol")

perhaps `%hookf(type, "/usr/lib/libname.dylib:symbol"` would make sense

**Comment by uroboro** [comment]
0eb6602 should allow doing this using:

```logos
%hookf(type, symbol, args) {}
%ctor {
	void * handle = dlopen("/usr/lib/libname.dylib", RTLD_LADY);
	%init(symbol = dlsym(handle, "symbol"));
}
```
