### ISSUE TITLE
Get pointers to original functions

### ISSUE THREAD

**Issue by pixelomer** [theos/logos#37]
Once a function is hooked using the Logos syntax (`%hook` or `%hookf`), it is no longer possible to call the original function from outside of the new function.

    %hook SomeClass
    
    // This is a method that is used and hooked by the tweak.
    - (id)someMethod:(id)someArg {
        // some stuff
        return somethingOtherThanOrig;
    }
    
    %end

    static void MyFunction() {
        // I want to call the original implementation but it is not possible to do that after %init.
        id value = [SomeClassInstance someMethod:NULL];

        // Maybe something like this?
        %origff(SomeClassInstance, "someMethod:", NULL);
    }

    %ctor {
        %init;
        MyFunction();
    }

**Comment by uroboro** [comment]
I was going over logos' source code to check some edge cases about the syntax and found out we never actually documented (on the iphonedevwiki nor here) the use of `%orig` prepended with an ampersand (`&%orig`). This is now documented in https://github.com/theos/logos/wiki/Syntax#orig-1.
