### ISSUE TITLE
%orig with different instance

### ISSUE THREAD

**Issue by pixelomer** [theos/logos#38]
There should be a way to call `%orig` with a different instance variable while not modifying `self`.

    // Maybe something like this?
    %origs(differentInstance); // Call %orig with different self and the original arguments
    %origs(differentInstance, NULL, 42, @NO); // Call %orig with different self and arguments

**Comment by NSExceptional** [comment]
Imo, this is too niche of a use case for Logos to add language-level support. But it has the same problem as your other issue: logos does not easily expose the original `IMP` for programmer use in any context. Maybe it should.

**Comment by uroboro** [comment]
It actually does, I just forgot to document it at the time and nobody else noticed since'. `&%orig` does this. This is now documented in https://github.com/theos/logos/wiki/Syntax#orig-1.

**Comment by NSExceptional** [comment]
It would be nice if we had a way to retrieve it without calling the method first, but that certainly takes care of a lot of use cases. Neat!

**Comment by uroboro** [comment]
Fetching the original function pointer from outside the hook means that you have to provide:
- group (optional defaulting to `_ungrouped`)
- class name
- method name

Then it would be some form of:

```logos
    UIImage * image = %orig_call(UIImage, "imageNamed:", @"duck"); // _ungrouped
    UIImage * image = %orig_call(myGroup, UIImage, "imageNamed:", @"rabbit");
```

which would require parsing the arguments to find which one is the selector string to know if there's a group being passed as first argument.

**Comment by NSExceptional** [comment]
Could just make the group last instead?
