### ISSUE TITLE
Decoupling from Theos

### ISSUE THREAD

**Issue by uroboro** [theos/logos#4]
There's a usage of `HBLogDebug` in [bin/lib/Logos/Generator/Base/Method.pm](https://github.com/theos/logos/blob/master/bin/lib/Logos/Generator/Base/Method.pm#L73) which is defined in [theos/headers/HBLog.h](https://github.com/theos/headers/blob/master/HBLog.h).

If Logos is truly meant to be decoupled, this logging facility has to be resolved in another manner, either as a builtin definition or a function name passed as a flag when running logos.pl. It should be taken into account that `HBLogDebug` is a macro that will end up expanding to `os_log_with_type` or `CFLog`.

**Comment by kirb** [comment]
Should be fine to switch back to just plain NSLog. It's the simplest choice, CFLog is private anyway so would require a dependency on the CFLogUtilities.h header. Color output from the HBLog macros was kinda necessary before os_log, now you can just filter to library == your binary name, so it's not really necessary. Could also use

```objc
#ifdef HBLogDebug
#define LogosLog HBLogDebug
#else
#define LogosLog NSLog
#endif
…
LogosLog(@"[%s:%i] blahblah", __FILE__, __LINE__, otherargs…);
```
