### ISSUE TITLE
Unnecessary warning for %property on non-object types

### ISSUE THREAD

**Issue by Muirey03** [theos/logos#40]
The code:
```
%property (nonatomic) BOOL newProperty;
```
will throw the warning:
```
warning: no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed
```
This warning is unnecessary. The normal objective-c compiler will not throw any warning for:
```
@property (nonatomic) BOOL newProperty;
```

**Comment by NSExceptional** [comment]
This has bugged me for a while. I've asked this before but I forget the answer. I'm sure @kirb can shed some light on this

**Comment by uroboro** [comment]
The warning has been there from the beginning: https://github.com/theos/logos/commit/c024e3de6a751f7b40c094ae571fe18206b3471a

**Comment by NSExceptional** [comment]
Yeah, but why is it *still* there? It's completely unnecessary in most cases

**Comment by uroboro** [comment]
Nobody complained and I rewrote it to keep the same functionality. I can remove the warning.
