### ISSUE TITLE
[Feature request] Support for specfiying image name for dynamic lookup of functions in %hookf

### ISSUE THREAD

**Issue by pwn20wndstuff** [theos/logos#47]
(https://github.com/theos/logos/commit/dd5477a12062244868a224565fb9b56d16aa853f)

Logos should also optimize multiple dynamic lookups with the same image name to increase performance. (e.g. MSGetImageByName should only be called once for two dynamic lookups with the same image name)

The return value of MSGetImageByName/MSFindSymbol should also be compared against NULL before calling MSFindSymbol/MSHookFunction to prevent a possible NULL pointer dereference.

**Comment by kirb** [comment]
I think @uroboro was considering whether to remove the dynamic lookup feature of %hookf, to encourage using dlsym()/MSFindSymbol() directly via %init (that bit was implemented in 0eb6602e). Which fixes this problem in a different, probably slightly unintuitive way.

**Comment by pwn20wndstuff** [comment]
Logos should still verify that it isn't passing NULL to MSHookFunction IMO.

**Comment by pwn20wndstuff** [comment]
I should have probably opened a new issue for that... But is there a way to access the original function (What you get when you call %orig inside the hook) outside of the hook without having to do dirty things like hardcoding the name logos generates for the old function pointer? e.g. hook func1 and call the original func1 inside of func2

**Comment by uroboro** [comment]
See the syntax page on this repository’s wiki on `&%orig`.

**Comment by pwn20wndstuff** [comment]
That's not exactly what I asked for -- I need to be able to get the original function pointer without requiring the hooked function to be called, not even for once. Maybe something like %orig(func, args...)

**Comment by kirb** [comment]
That’s what `&%orig` is - the `&` is part of the syntax preprocessed by Logos to signal that you want to get the original function pointer, you aren’t dereferencing the return value of the original function even though it does almost look that way.

Docs: https://github.com/theos/logos/wiki/Syntax#orig-1

**Comment by uroboro** [comment]
I’m closing this as the original issue was solved. Please open a new issue for different problems.
