### ISSUE TITLE
%c should cast the result to the input class type

### ISSUE THREAD

**Issue by NSExceptional** [theos/logos#56]
For example, `%c(Foo)` should evaluate to
```c
((Foo *) _logos_static_class_lookup$Foo())
```
instead of just
```c
_logos_static_class_lookup$Foo()
```
so that type information is not lost, allowing for things like `%c(Foo).classProperty`

**Comment by kirb** [comment]
I’m really certain we’ve had this discussion before. The problem is `Foo *` is the *instance type* of Foo, when `%c(Foo)` is giving you the *class type*. I don’t know of any way to return a Class correctly typed for the compiler.

**Comment by NSExceptional** [comment]
Ah, yes we have. I'm dumb. It's not possible AFAICT either

I wonder if new logos could just eagerly transform `%c(Foo).classProperty` to `[%c(Foo) classProperty]` then? That would personally go a long way for me
