### ISSUE TITLE
Tweak.x:5: error: %orig does not make sense outside a method (logify + making the tweak)

### ISSUE THREAD

**Issue by bloxploits** [theos/logos#61]
After I used logify on my methods and tried to make the tweak, this error occured:

Tweak.x:5: error: %orig does not make sense outside a method

**Comment by uroboro** [comment]
Can you share the file you provided to logify and the resulting file you got?

**Comment by L1ghtmann** [comment]
Closing due to lack of response. Feel free to reopen if the issue persists with the latest Logos.
