### ISSUE TITLE
Request: dot in class name support for %c

### ISSUE THREAD

**Issue by Muirey03** [theos/logos#62]
%c does not currently support class names such as `AppName.ClassName`, meaning `objc_getClass("AppName.ClassName")` must be used instead. It would be nice if `%c(AppName.ClassName)` could be used.

**Comment by NSExceptional** [comment]
I believe it does. Update Theos.

**Comment by Muirey03** [comment]
I was talking with uroboro and he didn't think it did and told me to make this issue, but I'll check.

**Comment by Muirey03** [comment]
Added in 57c507eb9ef2da5765b1b7aab785c032b117d56a

**Comment by uroboro** [comment]
Sorry about the confusion, a lot has been happening, and even now, this conversation seems farther than 4 days ago
