### ISSUE TITLE
Issue when using %property to add NSMutableArray with specified item type

### ISSUE THREAD

**Issue by Galactic-Dev** [theos/logos#68]
What are the steps to reproduce this issue?
-------------------------------------------
1. Use %property inside a hook like so: 
`%hook SomeClass
%property (nonatomic, retain) NSMutableArray  <Object *> *mutableArray;
%end
`
2. If you take out the `<Object *>` part, it compiles with no issue.
What happens?
-------------
Compiling the tweak results in an error: `error: expected identifier or '('
%property (nonatomic, retain) NSMutableArray <Object *> *mutableArray;`

What were you expecting to happen?
----------------------------------
The tweak to compile and the property to be added to the class.

Any logs, error output, etc?
----------------------------
Error is shown above.

What versions of software are you using?
----------------------------------------
**Operating System:** MacOS Catalina 10.15.6
**Toolchain Version:** clang v. 11.0.3 Xcode v. 11.6
**SDK Version:** 13.4

**Comment by kirb** [comment]
Indeed we don’t support the <…> generic portion, but we could for consistency. You should be able to work without it though, since the matching @property is what actually gets used by the compiler to determine the type. So:

```logos
@interface MyThing ()
@property (nonatomic, strong) NSMutableArray <MyItem *> *items;
@end

%hook MyThing
%property (nonatomic, strong) NSMutableArray *items;
%end
```

**Comment by Galactic-Dev** [comment]
Yeah I realized that a bit after I posted this, I'll close it since this is really a non-issue
