### ISSUE TITLE
Logos produces bad output without newline after imports

### ISSUE THREAD

**Issue by cxnder** [theos/logos#71]
repro:
`git clone https://github.com/KritantaDev/theosbug.git && cd theosbug && make package; make logos`

`make logos` will manually invoke logos.pl and create a `Tweak.m` file with the output of `logos.pl Tweak.x`.

---

Line 24 of `Tweak.m` output references the CGRect struct, however imports aren't done till Line 27. Both of these imports are the first thing in the Tweak.x file.

A newline fixes this.

Prefix.pch seems to have concealed this issue before iOS 14.

**Comment by kirb** [comment]
Forgot to close this after merging #73
