### ISSUE TITLE
iOSOpenDev compiles with logos.pl in Xcode 14.1 RC2 with numerous deprecation warnings

### ISSUE THREAD

**Issue by xybp888** [theos/logos#89]
/opt/theos/vendor/logos/bin/lib/Logos/Generator/Base/Property.pm 
# Getter
		$build .= " sprintf(_typeEncoding, \"%s\@:\", \@encode($propertyType));";
# Setter
		$build .= " sprintf(_typeEncoding, \"v\@:%s\", \@encode($propertyType));";

iOSOpenDev compiles with logos.pl in Xcode 14.1 RC2 with numerous deprecation warnings
	note: 
	warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead

Currently I myself use snprintf temporarily to get rid of the warning.

**Comment by PoomSmart** [comment]
#88

**Comment by xybp888** [comment]
Thanks!
