### ISSUE TITLE
Logos ignores end of block comment if line contains a `//` before block comment terminator

### ISSUE THREAD

**Issue by vr1s** [theos/logos#99]
The following code will reproduce this bug:
```
%hook SBIconListView

-(id)layoutProvider
{ return nil; }

-(NSInteger)screenType
{ return 0; }
%end

/* everything after this comment is // gone */

%hook KILLING
%new
-(void)KILLKILLKILL
{
    KILL();
}
%end
```
$THEOS/bin/logos.pl epictweak.x and note lack of killing

Any other comments?
-------------------
blindly assuming root cause is the wrong type of comment being processed before the other.

What versions of software are you using?
----------------------------------------
**Operating System:* macos
**Toolchain Version:** latest
**SDK Version:** latest

**Comment by L1ghtmann** [comment]
I believe this is resolved by https://github.com/theos/logos/pull/96

**Comment by vr1s** [comment]
Duplicate of #66 I'm blind
